export const INIT_TAB_INDEX = 'INIT_TAB_INDEX'
export const INIT_HOME_INFO = 'INIT_HOME_INFO'
export const INIT_AMOUNT_ED = 'INIT_AMOUNT_ED'
export const ADD_ACCOUNT_AMOUNT = 'ADD_ACCOUNT_AMOUNT'
export const NOTICE_DETAIL = 'NOTICE_DETAIL'

export const INIT_BANK_LIST = 'INIT_BANK_LIST'


export const TRANS_DETAIL = 'TRANS_DETAIL'


export const SD_INFO = 'SD_INFO'
export const SET_BG = 'SET_BG'
export const SET_HOME_AUTH_COLLECT_START = 'SET_HOME_AUTH_COLLECT_START'
